name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '7.3'
        ]

    steps:
        - uses: actions/checkout@v2

        - name: Composer install
          run: |
              composer --version
              composer install

        - name: Generate coverage report
          run: |
              composer run-script test-coverage
              vendor/bin/phpunit --coverage-clover=coverage.xml

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v2

  validation_php_7-3:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '7.3'
        ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          tools: composer:v2

      - name: Composer get cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer version
        run: composer --version

      - name: Composer install
        run: composer install

      - name: Run phpstan
        run: vendor/bin/phpstan analyse --error-format=github

      - name: Run phpcs
        run: composer cs-check

      - name: Run tests
        run: composer test

  validation_php_8-1:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '8.1'
        ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          tools: composer:v2

      - name: Composer get cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer version
        run: composer --version

      - name: Composer install
        run: composer install

      - name: Run tests
        run: composer test

  prefer-lowest:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '7.3'
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer prefer lowest
        run: composer lowest-setup

      - name: Run tests
        run: composer test

      - name: Validate prefer lowest
        run: composer lowest
